# Generated by Django 2.1.15 on 2020-06-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FulfilmentFilesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charity_name', models.CharField(max_length=100, null=True)),
                ('file_name', models.CharField(max_length=100, null=True)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('urn', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('firstname', models.CharField(max_length=100, null=True)),
                ('midname', models.CharField(max_length=100, null=True)),
                ('surname', models.CharField(max_length=100, null=True)),
                ('add1', models.CharField(max_length=100, null=True)),
                ('add2', models.CharField(max_length=100, null=True)),
                ('add3', models.CharField(max_length=100, null=True)),
                ('add4', models.CharField(max_length=100, null=True)),
                ('add5', models.CharField(max_length=100, null=True)),
                ('town', models.CharField(max_length=100, null=True)),
                ('county', models.CharField(max_length=100, null=True)),
                ('postcode', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('card_holders_name', models.CharField(max_length=100, null=True)),
                ('bank_account_number', models.IntegerField(null=True)),
                ('giftaid_decl', models.CharField(max_length=100, null=True)),
                ('frequency', models.CharField(max_length=100, null=True)),
                ('first_collection_date', models.DateField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('file_path', models.FileField(upload_to='data')),
            ],
        ),
    ]
