# Generated by Django 2.1.15 on 2020-07-22 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateField(auto_now_add=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('file_path', models.FileField(upload_to='data')),
                ('charity_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registration.CharityNames')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
