# Generated by Django 2.1.15 on 2020-07-22 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0001_initial'),
        ('fulfilment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merge_date', models.DateField(auto_now_add=True, null=True)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('charity_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registration.CharityNames')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FulfilmentFilesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urn', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('firstname', models.CharField(max_length=100, null=True)),
                ('midname', models.CharField(max_length=100, null=True)),
                ('surname', models.CharField(max_length=100, null=True)),
                ('add1', models.CharField(max_length=100, null=True)),
                ('add2', models.CharField(max_length=100, null=True)),
                ('add3', models.CharField(max_length=100, null=True)),
                ('add4', models.CharField(max_length=100, null=True)),
                ('add5', models.CharField(max_length=100, null=True)),
                ('town', models.CharField(max_length=100, null=True)),
                ('county', models.CharField(max_length=100, null=True)),
                ('postcode', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('card_holders_name', models.CharField(max_length=100, null=True)),
                ('bank_account_number', models.IntegerField(null=True)),
                ('giftaid_decl', models.CharField(max_length=100, null=True)),
                ('frequency', models.CharField(max_length=100, null=True)),
                ('first_collection_date', models.CharField(max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('charity_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registration.CharityNames')),
                ('file_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fulfilment.UploadFile')),
            ],
        ),
    ]
