# Generated by Django 2.1.15 on 2020-07-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfilment', '0002_downloadfile_fulfilmentfilesdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='file_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
