# Generated by Django 2.1.15 on 2020-06-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfilment', '0002_auto_20200625_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulfilmentfilesdata',
            name='first_collection_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
