# Generated by Django 2.1.15 on 2020-07-23 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
        ('fulfilment', '0003_uploadfile_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FulfilmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(blank=True, max_length=100, null=True)),
                ('charity_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registration.CharityNames')),
            ],
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='file_type',
        ),
    ]
