# Generated by Django 2.1.15 on 2020-07-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfilment', '0003_auto_20200629_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merge_date', models.DateField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('charity_name', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
