# Generated by Django 2.1.15 on 2020-07-23 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfilment', '0004_auto_20200723_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='file_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fulfilment.FulfilmentType'),
        ),
    ]
