# Generated by Django 2.1.15 on 2020-07-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfilment', '0006_auto_20200723_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fulfilmenttype',
            old_name='display_type',
            new_name='file_type',
        ),
        migrations.RenameField(
            model_name='uploadfile',
            old_name='system_type',
            new_name='file_type',
        ),
        migrations.RemoveField(
            model_name='fulfilmenttype',
            name='system_type',
        ),
    ]
