# Generated by Django 2.1.15 on 2020-07-30 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfilment', '0010_remove_fulfilmentfilesdata_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fulfilmentfilesdata',
            name='user_id',
        ),
    ]
