# Generated by Django 2.1.15 on 2020-07-30 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfilment', '0011_remove_fulfilmentfilesdata_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulfilmentfilesdata',
            name='upload_date',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='fulfilment.UploadFile'),
            preserve_default=False,
        ),
    ]
