# Generated by Django 2.1.15 on 2020-07-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfilment', '0012_fulfilmentfilesdata_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulfilmentfilesdata',
            name='upload_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
