# Generated by Django 2.1.15 on 2020-07-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharityNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.DateField(auto_now_add=True, null=True)),
                ('system_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
