# Generated by Django 2.1.15 on 2020-07-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
