# Generated by Django 2.1.15 on 2020-07-08 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_images_other'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='charity_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='images',
            name='other',
        ),
        migrations.RemoveField(
            model_name='images',
            name='username',
        ),
    ]
