# Generated by Django 2.1.15 on 2020-07-08 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_remove_images_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
